# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/images/bgDot.png) \
        $$quote($$BASEDIR/assets/images/buttons/1.png) \
        $$quote($$BASEDIR/assets/images/buttons/2.png) \
        $$quote($$BASEDIR/assets/images/buttons/3.png) \
        $$quote($$BASEDIR/assets/images/buttons/_chooseImage.png) \
        $$quote($$BASEDIR/assets/images/buttons/bbWorld.png) \
        $$quote($$BASEDIR/assets/images/buttons/goButton.png) \
        $$quote($$BASEDIR/assets/images/buttons/momentum.png) \
        $$quote($$BASEDIR/assets/images/buttons/momentumPressed.png) \
        $$quote($$BASEDIR/assets/images/buttons/setAsWall.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_add.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_clear.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_copy_quote.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_copy_quote_author.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_home.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_info.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_quote.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_reload.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_view_list.png) \
        $$quote($$BASEDIR/assets/images/logo.png) \
        $$quote($$BASEDIR/assets/images/splash/a.png) \
        $$quote($$BASEDIR/assets/images/splash/i.png) \
        $$quote($$BASEDIR/assets/images/splash/logo.png) \
        $$quote($$BASEDIR/assets/images/splash/m.png) \
        $$quote($$BASEDIR/assets/images/splash/p.png) \
        $$quote($$BASEDIR/assets/images/splash/r.png) \
        $$quote($$BASEDIR/assets/images/splash/s.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/0.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/1.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/10.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/11.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/12.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/13.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/14.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/15.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/16.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/17.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/2.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/3.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/4.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/5.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/6.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/7.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/8.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/9.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/0.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/1.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/10.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/11.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/12.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/13.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/14.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/15.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/16.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/17.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/2.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/3.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/4.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/5.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/6.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/7.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/8.png) \
        $$quote($$BASEDIR/assets/images/wallpapers/thumbs/9.png) \
        $$quote($$BASEDIR/assets/json/quotes.json) \
        $$quote($$BASEDIR/assets/json/words.json) \
        $$quote($$BASEDIR/assets/qml/colorTest.qml) \
        $$quote($$BASEDIR/assets/qml/helpPage.qml) \
        $$quote($$BASEDIR/assets/qml/infoPage.qml) \
        $$quote($$BASEDIR/assets/qml/listTest.qml) \
        $$quote($$BASEDIR/assets/qml/main.qml) \
        $$quote($$BASEDIR/assets/qml/momentumIntro.qml) \
        $$quote($$BASEDIR/assets/qml/momentumSetter.qml) \
        $$quote($$BASEDIR/assets/qml/quotePage.qml) \
        $$quote($$BASEDIR/assets/qml/settingsPage.qml) \
        $$quote($$BASEDIR/assets/qml/supportPage.qml) \
        $$quote($$BASEDIR/assets/qml/wordsDetails.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/MVC/QuotesItemProvider.cpp) \
        $$quote($$BASEDIR/src/MVC/WordsItemProvider.cpp) \
        $$quote($$BASEDIR/src/MomentumImageHelper.cpp) \
        $$quote($$BASEDIR/src/Pages/HelpPage.cpp) \
        $$quote($$BASEDIR/src/Pages/InfoPage.cpp) \
        $$quote($$BASEDIR/src/Pages/MomentumIntroPage.cpp) \
        $$quote($$BASEDIR/src/Pages/MomentumSetterPage.cpp) \
        $$quote($$BASEDIR/src/Pages/MomentumSetterThumb.cpp) \
        $$quote($$BASEDIR/src/Pages/QuotesDetailsPage.cpp) \
        $$quote($$BASEDIR/src/Pages/SettingsPage.cpp) \
        $$quote($$BASEDIR/src/Pages/SupportPage.cpp) \
        $$quote($$BASEDIR/src/Pages/WordsDetailsPage.cpp) \
        $$quote($$BASEDIR/src/SplashLetter.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/MVC/QuotesItemProvider.h) \
        $$quote($$BASEDIR/src/MVC/WordsItemProvider.h) \
        $$quote($$BASEDIR/src/MomentumImageHelper.h) \
        $$quote($$BASEDIR/src/Pages/HelpPage.h) \
        $$quote($$BASEDIR/src/Pages/InfoPage.h) \
        $$quote($$BASEDIR/src/Pages/MomentumIntroPage.h) \
        $$quote($$BASEDIR/src/Pages/MomentumSetterPage.h) \
        $$quote($$BASEDIR/src/Pages/MomentumSetterThumb.h) \
        $$quote($$BASEDIR/src/Pages/QuotesDetailsPage.h) \
        $$quote($$BASEDIR/src/Pages/SettingsPage.h) \
        $$quote($$BASEDIR/src/Pages/SupportPage.h) \
        $$quote($$BASEDIR/src/Pages/WordsDetailsPage.h) \
        $$quote($$BASEDIR/src/SplashLetter.h) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/MVC/*.c) \
        $$quote($$BASEDIR/../src/MVC/*.c++) \
        $$quote($$BASEDIR/../src/MVC/*.cc) \
        $$quote($$BASEDIR/../src/MVC/*.cpp) \
        $$quote($$BASEDIR/../src/MVC/*.cxx) \
        $$quote($$BASEDIR/../src/Pages/*.c) \
        $$quote($$BASEDIR/../src/Pages/*.c++) \
        $$quote($$BASEDIR/../src/Pages/*.cc) \
        $$quote($$BASEDIR/../src/Pages/*.cpp) \
        $$quote($$BASEDIR/../src/Pages/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/buttons/*.qml) \
        $$quote($$BASEDIR/../assets/images/buttons/*.js) \
        $$quote($$BASEDIR/../assets/images/buttons/*.qs) \
        $$quote($$BASEDIR/../assets/images/icons/*.qml) \
        $$quote($$BASEDIR/../assets/images/icons/*.js) \
        $$quote($$BASEDIR/../assets/images/icons/*.qs) \
        $$quote($$BASEDIR/../assets/images/splash/*.qml) \
        $$quote($$BASEDIR/../assets/images/splash/*.js) \
        $$quote($$BASEDIR/../assets/images/splash/*.qs) \
        $$quote($$BASEDIR/../assets/images/wallpapers/*.qml) \
        $$quote($$BASEDIR/../assets/images/wallpapers/*.js) \
        $$quote($$BASEDIR/../assets/images/wallpapers/*.qs) \
        $$quote($$BASEDIR/../assets/images/wallpapers/thumbs/*.qml) \
        $$quote($$BASEDIR/../assets/images/wallpapers/thumbs/*.js) \
        $$quote($$BASEDIR/../assets/images/wallpapers/thumbs/*.qs) \
        $$quote($$BASEDIR/../assets/json/*.qml) \
        $$quote($$BASEDIR/../assets/json/*.js) \
        $$quote($$BASEDIR/../assets/json/*.qs) \
        $$quote($$BASEDIR/../assets/qml/*.qml) \
        $$quote($$BASEDIR/../assets/qml/*.js) \
        $$quote($$BASEDIR/../assets/qml/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
